// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: proto/com/patruso/sboxed/tunnelmanager/v1/tunnel_manager_types.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package sboxed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WgPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *string `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *WgPeer) Reset() {
	*x = WgPeer{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WgPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgPeer) ProtoMessage() {}

func (x *WgPeer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgPeer.ProtoReflect.Descriptor instead.
func (*WgPeer) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{0}
}

func (x *WgPeer) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{1}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{2}
}

func (x *ListPeersResponse) GetPeerList() []*WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

type CreatePeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *CreatePeerRequest) Reset() {
	*x = CreatePeerRequest{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerRequest) ProtoMessage() {}

func (x *CreatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePeerRequest) GetPeerList() []*WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

type CreatePeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *CreatePeerResponse) Reset() {
	*x = CreatePeerResponse{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerResponse) ProtoMessage() {}

func (x *CreatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerResponse.ProtoReflect.Descriptor instead.
func (*CreatePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePeerResponse) GetPeerList() []*WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

type RemovePeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePeerRequest) GetPeerList() []*WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePeerResponse) GetPeerList() []*WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

type StartPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer *WgPeer `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *StartPeerRequest) Reset() {
	*x = StartPeerRequest{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPeerRequest) ProtoMessage() {}

func (x *StartPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPeerRequest.ProtoReflect.Descriptor instead.
func (*StartPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{7}
}

func (x *StartPeerRequest) GetPeer() *WgPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type StartPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StartPeerResponse) Reset() {
	*x = StartPeerResponse{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPeerResponse) ProtoMessage() {}

func (x *StartPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPeerResponse.ProtoReflect.Descriptor instead.
func (*StartPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{8}
}

func (x *StartPeerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StopPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer *WgPeer `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *StopPeerRequest) Reset() {
	*x = StopPeerRequest{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPeerRequest) ProtoMessage() {}

func (x *StopPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPeerRequest.ProtoReflect.Descriptor instead.
func (*StopPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{9}
}

func (x *StopPeerRequest) GetPeer() *WgPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type StopPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StopPeerResponse) Reset() {
	*x = StopPeerResponse{}
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPeerResponse) ProtoMessage() {}

func (x *StopPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPeerResponse.ProtoReflect.Descriptor instead.
func (*StopPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP(), []int{10}
}

func (x *StopPeerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto protoreflect.FileDescriptor

var file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDesc = []byte{
	0x0a, 0x44, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x74, 0x72,
	0x75, 0x73, 0x6f, 0x2f, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72,
	0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x2d, 0x0a, 0x06, 0x57,
	0x67, 0x50, 0x65, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5d,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74,
	0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5d, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72,
	0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72,
	0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x11,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x75,
	0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x12, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x75,
	0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3f, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78,
	0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72,
	0x22, 0x2b, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x52, 0x0a,
	0x0f, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3f, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f,
	0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65,
	0x72, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x74, 0x72,
	0x69, 0x63, 0x6b, 0x2d, 0x74, 0x72, 0x2f, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2d, 0x63, 0x6f,
	0x72, 0x65, 0x2d, 0x67, 0x6f, 0x3b, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescOnce sync.Once
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescData = file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDesc
)

func file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescGZIP() []byte {
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescOnce.Do(func() {
		file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescData)
	})
	return file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDescData
}

var file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_goTypes = []any{
	(*WgPeer)(nil),             // 0: com.patruso.sboxed.tunnelmanager.v1.WgPeer
	(*ListPeersRequest)(nil),   // 1: com.patruso.sboxed.tunnelmanager.v1.ListPeersRequest
	(*ListPeersResponse)(nil),  // 2: com.patruso.sboxed.tunnelmanager.v1.ListPeersResponse
	(*CreatePeerRequest)(nil),  // 3: com.patruso.sboxed.tunnelmanager.v1.CreatePeerRequest
	(*CreatePeerResponse)(nil), // 4: com.patruso.sboxed.tunnelmanager.v1.CreatePeerResponse
	(*RemovePeerRequest)(nil),  // 5: com.patruso.sboxed.tunnelmanager.v1.RemovePeerRequest
	(*RemovePeerResponse)(nil), // 6: com.patruso.sboxed.tunnelmanager.v1.RemovePeerResponse
	(*StartPeerRequest)(nil),   // 7: com.patruso.sboxed.tunnelmanager.v1.StartPeerRequest
	(*StartPeerResponse)(nil),  // 8: com.patruso.sboxed.tunnelmanager.v1.StartPeerResponse
	(*StopPeerRequest)(nil),    // 9: com.patruso.sboxed.tunnelmanager.v1.StopPeerRequest
	(*StopPeerResponse)(nil),   // 10: com.patruso.sboxed.tunnelmanager.v1.StopPeerResponse
}
var file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_depIdxs = []int32{
	0, // 0: com.patruso.sboxed.tunnelmanager.v1.ListPeersResponse.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	0, // 1: com.patruso.sboxed.tunnelmanager.v1.CreatePeerRequest.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	0, // 2: com.patruso.sboxed.tunnelmanager.v1.CreatePeerResponse.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	0, // 3: com.patruso.sboxed.tunnelmanager.v1.RemovePeerRequest.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	0, // 4: com.patruso.sboxed.tunnelmanager.v1.RemovePeerResponse.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	0, // 5: com.patruso.sboxed.tunnelmanager.v1.StartPeerRequest.peer:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	0, // 6: com.patruso.sboxed.tunnelmanager.v1.StopPeerRequest.peer:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_init() }
func file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_init() {
	if File_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto != nil {
		return
	}
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_goTypes,
		DependencyIndexes: file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_depIdxs,
		MessageInfos:      file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_msgTypes,
	}.Build()
	File_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto = out.File
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_rawDesc = nil
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_goTypes = nil
	file_proto_com_patruso_sboxed_tunnelmanager_v1_tunnel_manager_types_proto_depIdxs = nil
}
