// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: proto/com/patruso/sboxed/eventbus/v1/eventbus.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package v1

import (
	v1 "github.com/sboxed/tunnelmanager/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*EventEnvelope_CreatePeerEvent
	//	*EventEnvelope_RemovePeerEvent
	Event isEventEnvelope_Event `protobuf_oneof:"event"`
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescGZIP(), []int{0}
}

func (m *EventEnvelope) GetEvent() isEventEnvelope_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EventEnvelope) GetCreatePeerEvent() *CreatePeerEvent {
	if x, ok := x.GetEvent().(*EventEnvelope_CreatePeerEvent); ok {
		return x.CreatePeerEvent
	}
	return nil
}

func (x *EventEnvelope) GetRemovePeerEvent() *RemovePeerEvent {
	if x, ok := x.GetEvent().(*EventEnvelope_RemovePeerEvent); ok {
		return x.RemovePeerEvent
	}
	return nil
}

type isEventEnvelope_Event interface {
	isEventEnvelope_Event()
}

type EventEnvelope_CreatePeerEvent struct {
	CreatePeerEvent *CreatePeerEvent `protobuf:"bytes,1,opt,name=create_peer_event,json=createPeerEvent,proto3,oneof"`
}

type EventEnvelope_RemovePeerEvent struct {
	RemovePeerEvent *RemovePeerEvent `protobuf:"bytes,2,opt,name=remove_peer_event,json=removePeerEvent,proto3,oneof"`
}

func (*EventEnvelope_CreatePeerEvent) isEventEnvelope_Event() {}

func (*EventEnvelope_RemovePeerEvent) isEventEnvelope_Event() {}

type CreatePeerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*v1.WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *CreatePeerEvent) Reset() {
	*x = CreatePeerEvent{}
	mi := &file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerEvent) ProtoMessage() {}

func (x *CreatePeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerEvent.ProtoReflect.Descriptor instead.
func (*CreatePeerEvent) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePeerEvent) GetPeerList() []*v1.WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

type RemovePeerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*v1.WgPeer `protobuf:"bytes,1,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
}

func (x *RemovePeerEvent) Reset() {
	*x = RemovePeerEvent{}
	mi := &file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerEvent) ProtoMessage() {}

func (x *RemovePeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerEvent.ProtoReflect.Descriptor instead.
func (*RemovePeerEvent) Descriptor() ([]byte, []int) {
	return file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePeerEvent) GetPeerList() []*v1.WgPeer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

var File_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto protoreflect.FileDescriptor

var file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDesc = []byte{
	0x0a, 0x33, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x74, 0x72,
	0x75, 0x73, 0x6f, 0x2f, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x62, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x75,
	0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62,
	0x75, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x44, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x61, 0x74, 0x72, 0x75, 0x73, 0x6f, 0x2f, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2f,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x0d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x5d, 0x0a,
	0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x61, 0x74, 0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x11,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61,
	0x74, 0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x22, 0x5b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65,
	0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x61, 0x74, 0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x5b, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61,
	0x74, 0x72, 0x75, 0x73, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x78, 0x65, 0x64, 0x2e, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f,
	0x78, 0x65, 0x64, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescOnce sync.Once
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescData = file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDesc
)

func file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescGZIP() []byte {
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescOnce.Do(func() {
		file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescData)
	})
	return file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDescData
}

var file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_goTypes = []any{
	(*EventEnvelope)(nil),   // 0: com.patruso.sboxed.eventbus.v1.EventEnvelope
	(*CreatePeerEvent)(nil), // 1: com.patruso.sboxed.eventbus.v1.CreatePeerEvent
	(*RemovePeerEvent)(nil), // 2: com.patruso.sboxed.eventbus.v1.RemovePeerEvent
	(*v1.WgPeer)(nil),       // 3: com.patruso.sboxed.tunnelmanager.v1.WgPeer
}
var file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_depIdxs = []int32{
	1, // 0: com.patruso.sboxed.eventbus.v1.EventEnvelope.create_peer_event:type_name -> com.patruso.sboxed.eventbus.v1.CreatePeerEvent
	2, // 1: com.patruso.sboxed.eventbus.v1.EventEnvelope.remove_peer_event:type_name -> com.patruso.sboxed.eventbus.v1.RemovePeerEvent
	3, // 2: com.patruso.sboxed.eventbus.v1.CreatePeerEvent.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	3, // 3: com.patruso.sboxed.eventbus.v1.RemovePeerEvent.peer_list:type_name -> com.patruso.sboxed.tunnelmanager.v1.WgPeer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_init() }
func file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_init() {
	if File_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto != nil {
		return
	}
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_CreatePeerEvent)(nil),
		(*EventEnvelope_RemovePeerEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_goTypes,
		DependencyIndexes: file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_depIdxs,
		MessageInfos:      file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_msgTypes,
	}.Build()
	File_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto = out.File
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_rawDesc = nil
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_goTypes = nil
	file_proto_com_patruso_sboxed_eventbus_v1_eventbus_proto_depIdxs = nil
}
